from pydantic import BaseModel
from typing_extensions import Literal

class ChatMessage(BaseModel):
    """
    Represents a single message in a chat conversation.

    Attributes:
        content (str): The textual content of the message.

        role (Literal["assistant", "system", "user", "tool"]): The role of the author 
            of the message. Must be one of:
            - "assistant": Indicates the message is generated by the AI assistant.
            - "system": Provides high-level instructions or context for the chat.
            - "user": Represents input provided by the end user.
            - "tool": Indicates that the message is from an external tool or API.
    """
    content: str
    """The textual content of the message."""

    role: Literal["assistant", "system", "user", "tool"]
    """The role of the author of the message. Must be one of 'assistant', 'system', 'user', or 'tool'."""
